### ISSUE TITLE
taggings table: taggable_type --> tag_type

### ISSUE THREAD

**Issue by davidrunger** [j4sper/FlickrClone#2]
The varying model is not the thing getting tagged (the 'taggable' object). The thing that is varying is the category of tag. That being said -- and as much as I love polymorphic associations -- I'm not sure that we want separate region and topic tags. This will clutter up your views slightly (create a topic tag in this input, and use this other input for a region tag) and it might complicate/divide your search results as well. I wonder if anything would really be lost by simply mashing tags and topic tags into the same table?

**Comment by j4sper** [comment]
The reason for the two tag types was to allow search by geographic region. (i.e. give me all the photos from Japan not photos from a Japanese restaurant or Japantown in SF), but maybe I can do this with google maps instead.

**Comment by davidrunger** [comment]
Yeah, I see what you are saying. But on the other hand, the user has this massive map right in front of them, which they explicitly came to this page to use, so if they want photos from Japan then they're probably just going to zoom in on Japan in the map and find the photos that way, right? Maybe some users would want to type in 'Japan' instead, but that seems like a relatively small fraction of the expected use-cases, and might or might not be worth cluttering/complicating your views/DB/controllers etc. to provide that functionality. Your call to make, though. I can certainly see both sides of this issue.

**Comment by j4sper** [comment]
> the user has this massive map right in front of them, which they explicitly came to this page to use, so  if they want photos from Japan then they're probably just going to zoom in on Japan in the map and  find the photos that way

Good point... encourages users to use the map.
closed with: https://github.com/j4sper/FlickrClone/commit/3e5b92e709f68cb9ecacd34662b056c124bf4951
