### ISSUE TITLE
How exactly is the geocoding done?

### ISSUE THREAD

**Issue by davidrunger** [j4sper/FlickrClone#3]
I'm not clear on how the latitude/longitude data for the Google Maps API is going to be extracted. Will you be taking it out of exif data from the file uploads? Or will the user's be manually entering a location? How will this geocoding information be stored in the DB?

**Comment by j4sper** [comment]
Initially, I'll just have users manually enter lat and long, but eventually, I'd like users to be able to place a marker on the map to set the location.  I've updated the schema to include latitude and longitude columns in the photos table. https://github.com/j4sper/FlickrClone/commit/14f919ec65df0e9378d9bb62e2a8d74456b784c5

**Comment by davidrunger** [comment]
Nice! I'm guessing you'll want to make them floats rather than strings, too. Or does Google Maps API want "E" and "W" for longitudes. I'm guessing not...
